# Generated by Django 4.2.4 on 2024-08-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassword',
            name='username',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
